server:
  port: 7777

spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        # Configuracion para usar un repositorio Git
        # git:
        #   uri: http://github.com/mzrtcode/
        #   default-label: main
        #   clone-on-start: true
        native:
          search-locations: file:./config

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
