spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
  application:
    name: ms-companies
  profiles:
    deafult: default
  config:
    import: "optional:configserver:http://localhost:7777"
logging:
  level:
    hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 0
  servlet:
    context-path: /ms-companies

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka