spring:
  application:
    name: ms-companies
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: root
    password: toor
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

logging:
  level:
    hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 0
  servlet:
    context-path: /ms-companies

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka